name: Build, Push, and Deploy to ACI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      
      - name: Create Resource Group
        run: |
          az group create --name cv-resource-group --location "West Europe"

      
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mycvimage:latest
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}


      
      - name: Deploy ACI with Bicep
        run: |
          az deployment group create \
            --resource-group cv-resource-group \
            --template-file aci.bicep \
            --parameters image="${{ secrets.DOCKER_HUB_USERNAME }}/mycvimage:latest" containerName="mycvcontainer"

