name: Build, Push, and Deploy to ACI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group
        run: |
          az group create --name cv-resource-group --location "West Europe"

      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image to GHCR
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/jsvensson12/mycvimage:latest

      - name: Deploy ACI with Bicep
        run: |
          az deployment group create \
            --resource-group cv-resource-group \
            --template-file infrastructure/main.bicep \
            --parameters containerDeploy=true containerName="mycvcontainer" image="ghcr.io/jsvensson12/mycvimage:latest" location="West Europe"

