name: Build and test with Docker

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - name: checkout Repository
            uses: actions/checkout@v3

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2

          - name: Build and start container
            run: docker compose -f compose.yaml up --build -d

          - name: run tests
            run: |
               docker compose -f compose.yaml exec server npm test

          - name: Tear down container
            if: always()
            run: docker compose -f compose.yaml down


            
